web:
  build: .
  ports:
    - "80:80"
  links:
    - redis
    - postgres
  environment:
    - PGUSER=postgres
    - PGHOST=db
    - PGPASSWORD=password
postgres:
  image: mdillon/postgis:9.4
  environment:
    - POSTGRES_PASSWORD=password
  ports:
    - "5432:5432"
  command: postgres
redis:
  image: redis
