web:
  build: .
  ports:
    - "80:80"
  links:
    - cache
    - db

db:
  image: mdillon/postgis:9.4
  environment:
    - POSTGRES_PASSWORD=password
  ports:
    - "5432:5432"
  command: postgres

cache:
  image: redis
